const trips = [
  {
    id: 0,
    name: "ANG : 10 days",
    price: "2569.99",
    instock: 100,
    description:"Cruise to AI Anguilla island",
    imgSrc: "assets/t1.jpg",
  },
  {
    id: 1,
    name: "ANT : 6 days",
    price: 1835.99,
    instock: 43,
    description:"Cruise to AG Antigua & Barbuda island",
    imgSrc: "assets/t2.jpg",
  },
  {
    id: 2,
    name: "BHA : 11 days",
    price: 1999.99,
    instock: 10,
    description:"Cruise to BS Bahamas island",
    imgSrc: "assets/t3.jpg",
  },
  {
    id: 3,
    name: "BVI : 4 days",
    price: 4874.89,
    instock: 5,
    description:"Cruise to VG British Virgin Islands",
    imgSrc: "assets/t4.jpg",
  },
  {
    id: 4,
    name: "GRE : 7 days",
    price: 29139.903,
    instock: 4,
    description:"Cruise to GD Grenada ",
    imgSrc: "assets/t5.webp",
  },
  {
    id: 5,
    name: "ROS : 5 days",
    price: 3322.68,
    instock: 40,
    description:"Cruise to 	DM Dominica island",
    imgSrc: "assets/t6.jpg",
  },
];
